#!/bin/bash

# From http://jpmens.net/2012/07/05/shell-scripts-as-ansible-modules/
eval $(sed -e "s/\s?\([^=]+\)\s?=\s?\(\x22\([^\x22]+\)\x22|\x27\([^\x27]+\)\x27|\(\S+\)\)\s?/\1='\2'/p" $1)

# host
# port
# state present|absent
# file

if [ -z "$host" ]
then
  echo "{\"failed\": true, \"msg\": \"host is required, e.g. github.com\"}"
  exit 1
fi

# default state=present
if [ -z "$state" ]
then
  state="present"
fi

if [ "$state" != "present" -a "$state" != "absent" ]
then
  echo "{\"failed\": true, \"msg\": \"state must be 'present' or 'absent'\"}"
  exit 1
fi

# default port = 22
if [ -z "$port" ]
then
  port=22
fi

# default file = $HOME/.ssh/known_hosts
if [ -z "$file" ]
then
  file=$HOME/.ssh/known_hosts
fi

if [ ! -e "$file" ]
then
  mkdir -p $(dirname $file)
  touch $file
fi

ip=$(dig $host +short | tail -n1 )

keygen_name=$host
if [ -z "$port" -a $port -ne 22 ]
then
  keygen_name="[$host]:$port"
fi

have_host=$(ssh-keygen -F $keygen_name -f $file)
have_ip=$(ssh-keygen -F $ip -f $file)
have="$have_host$have_ip"

if [ -n "$have" -a $state == "absent" ]
then
  for h in $keygen_name $ip
  do
    ssh-keygen -R $h -f $file &> /dev/null
    if [ ! $? -eq 0 ]
    then
      echo "{\"failed\": true, \"msg\": \"Failed to remove host from known_hosts file\"}"
      exit 1
    fi
  done
  echo "{\"changed\": true}"
  exit
elif [ \( -z "$have_ip" -o -z "$have_host" \) -a $state == "present" ]
then
  result=0;
  if [ -z "$have_ip" ]; then
    ssh-keyscan -p $port -H $ip 2> /dev/null >> $file
    result=$(( $result + $? ))
  fi
  if [ -z "$have_host" ]; then
    ssh-keyscan -p $port -H $keygen_name 2> /dev/null >> $file
    result=$(( $result + $? ))
  fi
  if [ ! $result -eq 0 ]
    then
      echo "{\"failed\": true, \"msg\": \"Failed to add host to known_hosts file\"}"
      exit 1
    fi
  echo "{\"changed\": true}"
  exit
fi

echo "{\"changed\": false}"
exit
